// =============================================================================
// features/tests — icon registry
// -----------------------------------------------------------------------------
// Data files reference icons by STRING KEY (`IconKey`), never by import, so a
// new test page can pick an icon without touching a component. Everything here
// is a lucide glyph: the Figma frame uses a 1.75px-stroke rounded set, which
// lucide matches at `strokeWidth={1.75}`.
//
// Adding an icon = add one line to REGISTRY. Unknown keys render nothing (and
// warn in dev) rather than crashing the page.
// =============================================================================

import type { ComponentType } from 'react';
import {
  Activity,
  AirVent,
  AlertTriangle,
  Anchor,
  Apple,
  ArrowDown,
  ArrowRight,
  Award,
  Baby,
  BadgeCheck,
  Armchair,
  Bandage,
  BatteryLow,
  Biohazard,
  Bone,
  BookOpen,
  Box,
  Brain,
  Bug,
  Bed,
  BedDouble,
  CakeSlice,
  Calendar,
  ChartNoAxesCombined,
  CheckCircle2,
  Cigarette,
  Circle,
  CircleDot,
  Clock,
  Coffee,
  Compass,
  Cookie,
  Croissant,
  Cross,
  Dna,
  Droplet,
  Dumbbell,
  Eye,
  EyeOff,
  FileText,
  Film,
  Fish,
  FlaskConical,
  Flame,
  Frown,
  Footprints,
  Gem,
  Gift,
  Glasses,
  Globe,
  Grid2x2,
  HeartCrack,
  HeartPulse,
  Hourglass,
  Lamp,
  Landmark,
  Leaf,
  Lock,
  type LucideProps,
  MapPin,
  Maximize2,
  Microscope,
  MilkOff,
  Moon,
  Mountain,
  Network,
  Nut,
  Orbit,
  PersonStanding,
  PiggyBank,
  Pill,
  Ratio,
  Receipt,
  Rocket,
  Route,
  Plane,
  Salad,
  Scale,
  ScanHeart,
  Scissors,
  Search,
  Share2,
  ShieldCheck,
  ShieldPlus,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Target,
  Thermometer,
  Timer,
  Trees,
  Trophy,
  Truck,
  Users,
  Waves,
  Wheat,
  Wine,
  X,
  Zap,
} from 'lucide-react';

const REGISTRY: Record<string, ComponentType<LucideProps>> = {
  activity: Activity,
  alert: AlertTriangle,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  award: Award,
  baby: Baby,
  'badge-check': BadgeCheck,
  bone: Bone,
  box: Box,
  brain: Brain,
  calendar: Calendar,
  chart: ChartNoAxesCombined,
  check: CheckCircle2,
  clock: Clock,
  cross: Cross,
  droplet: Droplet,
  family: Network,
  file: FileText,
  film: Film,
  flask: FlaskConical,
  frown: Frown,
  hourglass: Hourglass,
  lock: Lock,
  microscope: Microscope,
  moon: Moon,
  person: PersonStanding,
  piggy: PiggyBank,
  'pregnancy-loss': HeartCrack,
  rocket: Rocket,
  scale: Scale,
  'scan-heart': ScanHeart,
  share: Share2,
  shield: ShieldCheck,
  smile: Smile,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  target: Target,
  truck: Truck,
  users: Users,
  x: X,
  zap: Zap,

  // ---- added for the Eye / Kidney / Men's / Skin panels -------------------
  acne: CircleDot,
  air: AirVent,
  alcohol: Wine,
  apple: Apple,
  caffeine: Coffee,
  cataract: Circle,
  cellulite: Grid2x2,
  cigarette: Cigarette,
  cyst: Orbit,
  dairy: MilkOff,
  dna: Dna,
  dumbbell: Dumbbell,
  eye: Eye,
  'eye-off': EyeOff,
  fish: Fish,
  flame: Flame,
  gem: Gem,
  glasses: Glasses,
  globe: Globe,
  gluten: Wheat,
  heart: HeartPulse,
  leaf: Leaf,
  omega: Fish,
  pressure: Ratio,
  receipt: Receipt,
  salad: Salad,
  salt: Sparkles,
  scissors: Scissors,
  'shield-plus': ShieldPlus,
  stretch: Maximize2,
  stroller: Baby,
  sugar: Cookie,
  sun: Sun,
  texture: Waves,
  tired: BatteryLow,
  trophy: Trophy,
  wrinkle: CakeSlice,

  // ---- added for the Immunity panel --------------------------------------
  bandage: Bandage,
  biohazard: Biohazard,
  pill: Pill,
  sick: Thermometer,
  stethoscope: Stethoscope,
  virus: Bug,

  // ---- added for the Ancestry panel --------------------------------------
  anchor: Anchor,
  book: BookOpen,
  compass: Compass,
  gift: Gift,
  landmark: Landmark,
  'map-pin': MapPin,
  mountain: Mountain,
  route: Route,
  search: Search,
  tag: Tag,
  trees: Trees,
  wheat: Wheat,

  // ---- added for the Sleep panel ------------------------------------------
  armchair: Armchair,
  bed: Bed,
  'bed-double': BedDouble,
  bread: Croissant,
  footprints: Footprints,
  lamp: Lamp,
  nut: Nut,
  plane: Plane,
  timer: Timer,
};

export function Icon({
  name,
  className,
  strokeWidth = 1.75,
}: {
  name?: string;
  className?: string;
  strokeWidth?: number;
}) {
  if (!name) return null;
  const Glyph = REGISTRY[name];
  if (!Glyph) {
    if (process.env.NODE_ENV !== 'production') {
      console.warn(`[tests/icons] unknown icon key "${name}" — add it to REGISTRY in icons.tsx`);
    }
    return null;
  }
  return <Glyph className={className} strokeWidth={strokeWidth} aria-hidden />;
}

export const ICON_KEYS = Object.keys(REGISTRY);

/** Kept as a named export for `Categories.tsx`, which predates the registry. */
export function Arrow({ className }: { className?: string }) {
  return <ArrowRight className={className} strokeWidth={1.75} aria-hidden />;
}
