import { z } from 'zod';

import { ETHNICITIES } from '../types';

/**
 * Runtime enforcement of the Neotech contract, section 7.
 *
 * WHY A VALIDATOR AT ALL, when TypeScript already describes the shape: because
 * everything that actually breaks here survives compilation. A date formatted
 * the American way is still a string. `testIds` with a space after the comma is
 * still a string. A payload assembled from database rows that were themselves
 * optional type-checks perfectly and is rejected on arrival.
 *
 * Their panel answers a bad payload with a generic rejection, so the difference
 * between catching it here and catching it there is the difference between a
 * field name and an afternoon.
 */

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/**
 * dd/mm/yyyy, and a real date.
 *
 * The regex alone would accept 31/02/2026. Round-tripping through Date is what
 * rejects it - a genomics order carrying an impossible collection date is worth
 * failing loudly over.
 */
export const neotechDate = z
  .string()
  .regex(/^\d{2}\/\d{2}\/\d{4}$/, 'Dates must be dd/mm/yyyy')
  .refine((v) => {
    const [d, m, y] = v.split('/').map(Number) as [number, number, number];
    if (m < 1 || m > 12 || d < 1) return false;
    const probe = new Date(Date.UTC(y, m - 1, d));
    return probe.getUTCFullYear() === y && probe.getUTCMonth() === m - 1 && probe.getUTCDate() === d;
  }, 'Not a real calendar date');

/** HH:mm, or empty - their own records frequently leave collection time blank. */
export const neotechTime = z.union([
  z.literal(''),
  z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'Time must be HH:mm'),
]);

/**
 * Comma-separated test ids with NO spaces, even when there is only one.
 *
 * Split-and-rejoin rather than one clever regex, so the error can say which
 * element is wrong. `NMC-WL01.04` shows the shape: prefix, panel, optional
 * two-digit sub-panel.
 */
export const testIdsCsv = z
  .string()
  .min(1, 'testIds is required')
  .refine((v) => !/\s/.test(v), 'testIds must contain no whitespace - "A,B", never "A, B"')
  .refine((v) => !v.startsWith(',') && !v.endsWith(',') && !v.includes(',,'), 'testIds has an empty element')
  .refine(
    (v) => v.split(',').every((id) => /^[A-Z]{2,4}-[A-Z0-9]+(\.\d{2})?$/.test(id)),
    'Each test id must look like NMC-CT01 or NMC-WL01.04'
  );

// ---------------------------------------------------------------------------
// Enums - values exactly as their form posts them
// ---------------------------------------------------------------------------

export const genderEnum = z.enum(['M', 'F', 'O']);
/** The cm multiplier, not the unit name. Rule 4. */
export const heightUnitEnum = z.enum(['1', '2.54', '30.48']);
export const sampleTypeEnum = z.enum(['SALIVA', 'BLOOD', 'SWAB', 'BUCCAL SWAB']);
export const smokingEnum = z.enum(['No', 'Yes']);
export const alcoholicEnum = z.enum(['No', 'Occasional', 'Regular', 'Drunkyard']);
export const lifestyleEnum = z.enum(['No Activity', 'Light Activity', 'Moderate Activity', 'Extreme Activity']);
export const yesNoEnum = z.enum(['Yes', 'No']);
export const ethnicityEnum = z.enum(ETHNICITIES);

// ---------------------------------------------------------------------------
// Objects
// ---------------------------------------------------------------------------

export const familyHistoryEntrySchema = z.object({
  condition: z.string().min(1),
  relationship: z.string().min(1),
});

export const patientHistorySchema = z.object({
  patientHistory: z.string().default(''),
  smoking: smokingEnum,
  alcoholic: alcoholicEnum,
  medicalHistory: z.string().default(''),
  medication: z.string().default(''),
  familyHistory: z.array(familyHistoryEntrySchema).default([]),
});

export const patientSchema = z
  .object({
    // Minted by them. Validated in shape only, so a value we somehow acquired is
    // checked, but never required - and never generated by us. Rule 10.
    patientId: z
      .string()
      .regex(/^KYG\d{6}\d{3}$/, 'patientId is KYG + YYMMDD + 3 digits, and is issued by Neotech')
      .optional(),

    // Rule 8 - the required set. Anything absent here is rejected on arrival.
    patientFName: z.string().min(1, 'patientFName is required'),
    patientMName: z.string().optional(),
    patientLName: z.string().optional(),
    gender: genderEnum,
    dob: neotechDate.optional(),
    age: z.number().int().min(0).max(130),
    height: z.number().positive('height is required'),
    unit: heightUnitEnum,
    weight: z.number().positive('weight is required'),
    ethinicity: ethnicityEnum,

    mrno: z.string().optional(),
    address: z.string().optional(),
    city: z.string().optional(),
    country: z.string().optional(),
    phoneNo: z.string().optional(),
    mobileNo: z.string().optional(),
    email: z.string().email().or(z.literal('')).optional(),
    nationality: z.string().optional(),
    lifestyle: lifestyleEnum.optional(),

    // Rule 9. Modelled as a literal rather than the Yes/No enum because "No" is
    // not a state an order may be raised in - there is nothing to decide here.
    isPatientConsent: z.literal('Yes', {
      message: 'Patient consent must be Yes before an order can be raised',
    }),

    history: patientHistorySchema.optional(),
  })
  .refine(
    (p) => {
      // When both are present they must agree. A dob that does not produce the
      // stated age means one of the two is wrong, and their panel derives age
      // from dob - so it would silently overwrite ours.
      if (!p.dob) return true;
      const [d, m, y] = p.dob.split('/').map(Number) as [number, number, number];
      const now = new Date();
      let derived = now.getUTCFullYear() - y;
      const beforeBirthday = now.getUTCMonth() + 1 < m || (now.getUTCMonth() + 1 === m && now.getUTCDate() < d);
      if (beforeBirthday) derived -= 1;
      return Math.abs(derived - p.age) <= 1;
    },
    { message: 'age does not match dob', path: ['age'] }
  );

/**
 * THE SPEC CONTRADICTS ITSELF HERE, and the disagreement is left visible rather
 * than resolved by guesswork.
 *
 * Section 3.1 marks `doctorFName` required, and rule 8 lists it among the fields
 * whose absence gets a payload rejected. But the canonical example in section 6
 * - copied from their own panel - carries `"doctorFName": ""`. Both cannot be
 * true, and only their live endpoint can settle it.
 *
 * The default is STRICT, because section 7 opens with "do not deviate" and
 * because a rejected payload is a cheaper mistake than a silently orphaned
 * order. It matters for us specifically: we are direct-to-consumer, so most
 * orders genuinely have no referring clinician, and if their panel does accept a
 * blank the strict reading forces us to invent a doctor for every order.
 *
 * Confirm against their panel, then set the default accordingly and delete this
 * comment. Until then the flag documents an open question instead of hiding one.
 */
export const specialistSchema = z.object({
  doctorFName: z.string().min(1, 'doctorFName is required'),
  doctorLName: z.string().optional(),
  hospital: z.string().optional(),
  clinic: z.string().optional(),
  docMobileNo: z.string().optional(),
  docEmail: z.string().email().or(z.literal('')).optional(),
});

/** The section-6 reading: a blank referring doctor is acceptable. */
export const specialistSchemaLenient = specialistSchema.extend({
  doctorFName: z.string(),
});

export const testSchema = z.object({
  testName: z.string().min(1),
  testIds: testIdsCsv,
  expectedTAT: neotechDate,
  status: z.string().optional(),
});

export const sampleSchema = z.object({
  sampleId: z.string().min(1, 'sampleId is required'),
  sampleType: sampleTypeEnum,
  testDate: neotechDate,
  testTime: neotechTime.optional(),
  tests: z.array(testSchema).min(1, 'A sample must carry at least one test'),
});

export const shipmentSchema = z.object({
  shipmentNo: z
    .string()
    .regex(/^SHKYG\d{6}\d{4}$/, 'shipmentNo is SH + KYG + YYMMDD + 4 digits, and is issued by Neotech')
    .optional(),
  courierNo: z.string().min(1),
  courierDate: neotechDate,
  courierService: z.string().min(1),
  orders: z.array(z.string()).optional(),
  status: z.string().optional(),
});

export const amiSchema = z.object({
  chestPain: z.boolean().optional(),
  cardiacEnzyme: z.boolean().optional(),
  cholestrol: z.number().nonnegative().optional(),
  hdl: z.number().nonnegative().optional(),
  cholestrolHdlRatio: z.number().nonnegative().optional(),
  ldl: z.number().nonnegative().optional(),
  hdl_ldlRatio: z.number().nonnegative().optional(),
  triglycerides: z.number().nonnegative().optional(),
  hbValue: z.number().nonnegative().optional(),
  bp_systolic: z.number().int().positive().optional(),
  bp_diastolic: z.number().int().positive().optional(),
  medications: z.string().optional(),
  echocardiography: z.string().optional(),
  nct: z.string().optional(),
  metabolomeRatio: z.string().optional(),
});

function buildOrderSchema(specialist: typeof specialistSchema | typeof specialistSchemaLenient) {
  return z
    .object({
      orderNo: z
        .string()
        .regex(/^OR-\d{6}\d{5}$/, 'orderNo is OR- + YYMMDD + 5 digits, and is issued by Neotech')
        .optional(),
      orderDate: neotechDate,
      patient: patientSchema,
      specialist,
      samples: z.array(sampleSchema).min(1, 'An order must carry at least one sample'),
      externalRef: z.string().optional(),
      shipment: shipmentSchema.optional(),
      ami: amiSchema.optional(),
    })
    .superRefine((order, ctx) => {
      // Rule 6 says one sampleId may span several TEST blocks, which it does -
      // within a sample. Two SAMPLE entries sharing an id is a different thing:
      // it means we split one physical tube into two records, and their panel
      // would treat the second as a duplicate barcode.
      const seen = new Set<string>();
      order.samples.forEach((s, i) => {
        if (seen.has(s.sampleId)) {
          ctx.addIssue({
            code: 'custom',
            message: `sampleId "${s.sampleId}" appears on more than one sample - put its tests in one sample block`,
            path: ['samples', i, 'sampleId'],
          });
        }
        seen.add(s.sampleId);
      });

      // A panel is one test with several ids. The same id turning up under two
      // test names means the mapping table has a collision.
      const idOwner = new Map<string, string>();
      order.samples.forEach((s, si) =>
        s.tests.forEach((t, ti) =>
          t.testIds.split(',').forEach((id) => {
            const prev = idOwner.get(id);
            if (prev && prev !== t.testName) {
              ctx.addIssue({
                code: 'custom',
                message: `test id ${id} is claimed by both "${prev}" and "${t.testName}"`,
                path: ['samples', si, 'tests', ti, 'testIds'],
              });
            }
            idOwner.set(id, t.testName);
          })
        )
      );
    });
}

export const orderSchema = buildOrderSchema(specialistSchema);
/** As above, but tolerating the blank `doctorFName` the section-6 example carries. */
export const orderSchemaLenient = buildOrderSchema(specialistSchemaLenient);

export type ValidatedOrder = z.infer<typeof orderSchema>;

export interface ValidateOptions {
  /**
   * Whether a referring clinician must be named. Defaults to true, per rule 8.
   * See the note on specialistSchema - their own example disagrees with it.
   */
  requireSpecialist?: boolean;
}

/**
 * Parses, and on failure reports every problem at once.
 *
 * Their panel rejects on the first fault it hits, so submitting to learn what is
 * wrong costs one round trip per field. Returning the whole list makes fixing a
 * payload a single pass.
 */
export function validateNeotechOrder(
  input: unknown,
  opts: ValidateOptions = {}
): { ok: true; order: ValidatedOrder } | { ok: false; errors: string[] } {
  const schema = opts.requireSpecialist === false ? orderSchemaLenient : orderSchema;
  const result = schema.safeParse(input);
  if (result.success) return { ok: true, order: result.data };
  return {
    ok: false,
    errors: result.error.issues.map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`),
  };
}
